version: '3.2.0'

services:
  llm:
    container_name: ollama-llm
    image: ollama/ollama
    ports:
      - "11434:11434"

  unstructured:
    container_name: unstructured-document-loader
    image : downloads.unstructured.io/unstructured-io/unstructured-api
    ports: 
      - "8000:8000"

  askmypaper:
    container_name: askmypaper
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    